### ISSUE TITLE
Error code: 012-1511 when trying to open Miiverse on 3DS.

### ISSUE THREAD

**Issue by The4thPlayer** [PretendoNetwork/.github#30] opened 2023-10-06 18:08 UTC
It says, "There is a problem with the certificate for this page.
            Allow connection anyway?
            (This is not recommended.)
            
Error Details
            Certificate not found."
Certificate Subject
Certificate Issuer
Issue Date
            1/1/2000 0:00:00
            Expiration Date
            1/1/2000 0:00:00"
If I select either (B) Reject, or (A) Allow, I get this error.
"Error code: 000-0000"
                 Communication error."

Is there anything I can do to fix this? Or is Juxt down right now?

**Comment by SomeonesGarbage** [comment] 2023-10-16 14:16
try asking on the discord server

**Comment by The4thPlayer** [comment] 2023-11-06 13:37
I don't use discord.

**Comment by jonbarrow** [comment] 2024-06-25 14:57
This is likely caused by you not having installed the correct certificate, as mentioned by the above comment. Closing for lack of details. If the issue persists even after doing a correct installation this can be reopened

**Closed by jonbarrow** 2024-06-25 14:57 UTC
