### ISSUE TITLE
Error 104-2210

### ISSUE THREAD

**Issue by emmanu888** [PretendoNetwork/.github#45] opened 2024-04-10 01:26 UTC
I followed the instructions and everything was working so i redid the modification to add the Splatoon 2 maps to private battles and i started getting the error again.

This might be worth looking into as right now, it might look like those maps aren't going to be playable for the time being since it seems the modification required to host games with those maps will trigger error 104-2210 to appear.

**Comment by dogmann112** [comment] 2024-04-12 22:18
Which instructions do you mean?

**Comment by jonbarrow** [comment] 2024-04-13 17:37
> i redid the modification to add the Splatoon 2 maps to private battles

While we allow mods which do not harm the gameplay experiences of other users, we do not provide direct support for errors when mods are used unless it's a mod that we explicitly acknowledge

It's not possible to know if the issue is on our end or on yours when you have mods installed. Uninstall the mods and try again in the vanilla game

Also try deleting your Splatoon shared data and trying again

**Comment by jonbarrow** [comment] 2024-06-25 14:43
Closing since this is not the right repository for this issue and I'm cleaning up issues. 104-XXXX errors are for the BOSS server. Our BOSS server has gotten lots of upgrades recently which likely fix this, if it was even an issue on our end. But again we do not provide direct support for modded environments like this, as any issues caused by them are our of our hands

**Closed by jonbarrow** 2024-06-25 14:43 UTC
