### ISSUE TITLE
Can´t open homebrews

### ISSUE THREAD

**Issue by Filippobob20** [PretendoNetwork/.github#12] opened 2022-10-04 23:23 UTC
when i install the pretendo network i can´t open homebrews it only shows up a black screen

**Comment by FavroiteGamers** [comment] 2022-10-29 23:23
I have the same issue I just remove nimble and put it back in after using the homebrew applications

**Comment by jonbarrow** [comment] 2024-06-25 14:50
Closing as this was likely caused by us trying to support Tiramisu (which breaks compatibility with older homebrew), which we no longer do

**Closed by jonbarrow** 2024-06-25 14:50 UTC
